[package]
name = "getting-started"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
chrono = "0.4.42"
derived-cms = { path = "../..", features = ["sqlite", "json"] }
ormlite = { version = "0.23.3", features = ["default-sqlite"] }
serde = "1.0.228"
serde_with = "3.16.1"
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "tls-rustls-ring-webpki",
] }
thiserror = "2.0.17"
tokio = "1.49.0"
ts-rs = "10.1.0"
uuid = { version = "1.19.0", features = ["v4"] }
